### PR TITLE
Set target channel via environment variable

### LINKED ISSUE #1: Make the Slack channel configurable
Right now all messages will be posted in #servers. There should be an option to configure the target channel - which would also help to avoid spam in the channel during development.

### PR DESCRIPTION
**Pull request by allesmi**
Fixes #1

### CODE REVIEW

**Comment by mpreis** [comment]
Nice idea, but why not passing the channel as a parameter? In my opinion this would be the preferred implementation, because it's more flexible than an environment variable.

A scenario could be: While experiment setup all messages should be sent to me personally, but when starting the actual experiment the server channel should be informed (because the experiment is performance sensitive, ...).

**Comment by allesmi** [comment]
Why not both:
A site-wide configuration via environment variable and a parameter for one-off messages?

**Comment by mpreis** [comment]
Both would be awesome. So that there is a default channel, but if required this is overruled by a given parameter.

**Comment by mpreis** [comment]
thank you, @allesmi.

**Pull request merged**
